In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("financial_dataset.csv")

In [3]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [276]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00

In [277]:
df.tail()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [278]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    2000 non-null   int64
 1   Customer_ID       2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Category          1977 non-null   object
 4   Sales             1967 non-null   float64
 5   Profit            1970 non-null   float64
 6   Quantity          2000 non-null   int64
 7   Payment_Status    2000 non-null   object
 8   City              1979 non-null   object
 9   Transaction_Date  2000 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 156.4+ KB

In [279]:
df.describe()

       Transaction_ID         Sales        Profit    Quantity
count     2000.000000   1967.000000   1970.000000  2000.00000
mean     11001.443500  25147.046263   3469.098985    10.18850
std        578.772536  14375.624741   4923.386360     5.52958
min      10001.000000    516.000000  -4982.000000     1.00000
25%      10502.750000  12723.500000   -812.500000     5.00000
50%      10998.500000  25200.000000   3526.000000    10.00000
75%      11504.250000  37545.000000   7711.250000    15.00000
max      12000.000000  49923.000000  11988.000000    19.00000

In [280]:
df.shape

(2000, 10)

In [281]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Customer_Name        0
Category            23
Sales               33
Profit              30
Quantity             0
Payment_Status       0
City                21
Transaction_Date     0
dtype: int64

In [282]:
df["Category"]

0         Furniture
1        Stationery
2              food
3         Furniture
4        Stationery
           ...
1995    Electronics
1996    Electronics
1997           Food
1998      Furniture
1999       Clothing
Name: Category, Length: 2000, dtype: object

In [283]:
df["Category"].mode()

0    Clothing
Name: Category, dtype: object

In [284]:
df["Category"].fillna(0)

0         Furniture
1        Stationery
2              food
3         Furniture
4        Stationery
           ...
1995    Electronics
1996    Electronics
1997           Food
1998      Furniture
1999       Clothing
Name: Category, Length: 2000, dtype: object

In [285]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [286]:
df["Category"]

0         Furniture
1        Stationery
2              food
3         Furniture
4        Stationery
           ...
1995    Electronics
1996    Electronics
1997           Food
1998      Furniture
1999       Clothing
Name: Category, Length: 2000, dtype: object

In [287]:
df["Sales"]

0        1875.0
1       32521.0
2        8948.0
3       20072.0
4       32943.0
         ...
1995    14407.0
1996     2105.0
1997    35927.0
1998    48447.0
1999     8433.0
Name: Sales, Length: 2000, dtype: float64

In [288]:
df["Sales"].mean()

np.float64(25147.046263345197)

In [289]:
df["Sales"].fillna(30)

0        1875.0
1       32521.0
2        8948.0
3       20072.0
4       32943.0
         ...
1995    14407.0
1996     2105.0
1997    35927.0
1998    48447.0
1999     8433.0
Name: Sales, Length: 2000, dtype: float64

In [290]:
df["Sales"]=df["Sales"].fillna(df["Sales"].mean())

In [291]:
df["Sales"]

0        1875.0
1       32521.0
2        8948.0
3       20072.0
4       32943.0
         ...
1995    14407.0
1996     2105.0
1997    35927.0
1998    48447.0
1999     8433.0
Name: Sales, Length: 2000, dtype: float64

In [292]:
df["Profit"]

0       4126.0
1       9290.0
2       8683.0
3       8320.0
4       9336.0
         ...
1995    9016.0
1996    5292.0
1997    2756.0
1998    1654.0
1999    4718.0
Name: Profit, Length: 2000, dtype: float64

In [293]:
df["Profit"].median()

3526.0

In [294]:
df["Profit"].fillna(0)

0       4126.0
1       9290.0
2       8683.0
3       8320.0
4       9336.0
         ...
1995    9016.0
1996    5292.0
1997    2756.0
1998    1654.0
1999    4718.0
Name: Profit, Length: 2000, dtype: float64

In [295]:
df["Profit"]=df["Profit"].fillna(df["Profit"].median())

In [296]:
df["Profit"]

0       4126.0
1       9290.0
2       8683.0
3       8320.0
4       9336.0
         ...
1995    9016.0
1996    5292.0
1997    2756.0
1998    1654.0
1999    4718.0
Name: Profit, Length: 2000, dtype: float64

In [297]:
df["City"]

0          Mumbai
1       Bangalore
2         Chennai
3          Mumbai
4       Bangalore
          ...
1995    Bangalore
1996        Delhi
1997    Mangalore
1998        Delhi
1999        Kochi
Name: City, Length: 2000, dtype: object

In [298]:
df["City"].mode()

0    Delhi
Name: City, dtype: object

In [299]:
df["City"].fillna(0)

0          Mumbai
1       Bangalore
2         Chennai
3          Mumbai
4       Bangalore
          ...
1995    Bangalore
1996        Delhi
1997    Mangalore
1998        Delhi
1999        Kochi
Name: City, Length: 2000, dtype: object

In [300]:
df["City"]=df["City"].fillna(df["Profit"].mode()[0])

In [301]:
df["City"]

0          Mumbai
1       Bangalore
2         Chennai
3          Mumbai
4       Bangalore
          ...
1995    Bangalore
1996        Delhi
1997    Mangalore
1998        Delhi
1999        Kochi
Name: City, Length: 2000, dtype: object

In [302]:
df.isnull().sum()

Transaction_ID      0
Customer_ID         0
Customer_Name       0
Category            0
Sales               0
Profit              0
Quantity            0
Payment_Status      0
City                0
Transaction_Date    0
dtype: int64

In [245]:
df=df.drop_duplicates()

In [246]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [247]:
df["Category"]=df["Category"].str.title()

In [248]:
df["Category"]

0         Furniture
1        Stationery
2              Food
3         Furniture
4        Stationery
           ...
1995    Electronics
1996    Electronics
1997           Food
1998      Furniture
1999       Clothing
Name: Category, Length: 1960, dtype: object

In [249]:
df["Payment_Status"]=df["Payment_Status"].str.title()

In [250]:
df["Payment_Status"]

0       Pending
1          Paid
2        Unpaid
3       Pending
4          Paid
         ...
1995       Paid
1996     Unpaid
1997    Pending
1998     Unpaid
1999    Pending
Name: Payment_Status, Length: 1960, dtype: object

In [251]:
df["Category"]=df["Category"].str.strip()

In [252]:
df["Category"]

0         Furniture
1        Stationery
2              Food
3         Furniture
4        Stationery
           ...
1995    Electronics
1996    Electronics
1997           Food
1998      Furniture
1999       Clothing
Name: Category, Length: 1960, dtype: object

In [253]:
df["Payment_Status"]=df["Payment_Status"].str.title()

In [254]:
df["Payment_Status"]

0       Pending
1          Paid
2        Unpaid
3       Pending
4          Paid
         ...
1995       Paid
1996     Unpaid
1997    Pending
1998     Unpaid
1999    Pending
Name: Payment_Status, Length: 1960, dtype: object

In [255]:
df["City"]=df["City"].str.strip()

In [256]:
df["City"]

0          Mumbai
1       Bangalore
2         Chennai
3          Mumbai
4       Bangalore
          ...
1995    Bangalore
1996        Delhi
1997    Mangalore
1998        Delhi
1999        Kochi
Name: City, Length: 1960, dtype: object

In [10]:
df["Transaction_Date"]=pd.to_datetime(df["Transaction_Date"])
df.dtypes

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [11]:
df.duplicated().sum()

np.int64(40)

In [12]:
df=df.drop_duplicates()

In [13]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [14]:
df.to_csv("cleaaned_financial_dataset.csv",
          index=False)

In [9]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [7]:
print("database cleaned successfully")
df

database cleaned successfully

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00