In [77]:
import pandas as pd

In [78]:
df=pd.read_csv("financial_transactions.csv")

In [79]:
df

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [80]:
df.shape

(500, 10)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  500 non-null    int64
 1   Date            500 non-null    object
 2   Customer        500 non-null    object
 3   Category        500 non-null    object
 4   Product         500 non-null    object
 5   Quantity        500 non-null    int64
 6   Sales           500 non-null    int64
 7   Profit          500 non-null    int64
 8   Payment_Method  500 non-null    object
 9   Region          500 non-null    object
dtypes: int64(4), object(6)
memory usage: 39.2+ KB

In [82]:
df.head()

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North

In [83]:
df.tail()

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [84]:
df.columns

Index(['Transaction_ID', 'Date', 'Customer', 'Category', 'Product', 'Quantity',
       'Sales', 'Profit', 'Payment_Method', 'Region'],
      dtype='object')

In [85]:
df.isnull().sum()

Transaction_ID    0
Date              0
Customer          0
Category          0
Product           0
Quantity          0
Sales             0
Profit            0
Payment_Method    0
Region            0
dtype: int64

In [86]:
df.describe()

       Transaction_ID    Quantity          Sales        Profit
count      500.000000  500.000000     500.000000     500.00000
mean       250.500000    5.588000   77935.808000   14718.44400
std        144.481833    2.884944  122810.672351   25053.37623
min          1.000000    1.000000     111.000000      11.00000
25%        125.750000    3.000000    6823.250000    1203.75000
50%        250.500000    6.000000   20646.000000    3654.00000
75%        375.250000    8.000000   94242.000000   16099.50000
max        500.000000   10.000000  747490.000000  156830.00000

In [87]:
df.duplicated().sum()

np.int64(0)

In [88]:
df=df.drop_duplicates()

In [89]:
df

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [90]:
hight_sales=df[df["Sales"]>60000]

In [91]:
hight_sales

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South
14,15,2026-04-22,Priya,Electronics,Keyboard,5,230435,24090,UPI,North
15,16,2026-08-11,Divya,Furniture,Desk,3,105813,29709,Net Banking,South
...,...,...,...,...,...,...,...,...,...,...
485,486,2026-04-09,Pooja,Electronics,Monitor,10,436840,83394,Net Banking,South
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South
494,495,2026-08-22,Neha,Electronics,Headphones,4,238292,62574,Net Banking,South
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North

In [92]:
hight_sales=df[df["Profit"]>1000]

In [93]:
hight_sales

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
5,6,2026-06-08,Neha,Grocery,Rice,9,11250,2952,Net Banking,South
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [94]:
hight_sales=df[df["Region"]=="North"]

In [95]:
hight_sales

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
13,14,2026-04-30,Nikhil,Grocery,Biscuits,2,3252,533,Debit Card,North
...,...,...,...,...,...,...,...,...,...,...
476,477,2026-04-16,Meena,Furniture,Chair,8,25312,2596,Net Banking,North
491,492,2026-06-26,Divya,Clothing,Jacket,5,8495,2248,Credit Card,North
493,494,2026-04-17,Ravi,Stationery,Marker,1,1947,319,Net Banking,North
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North

In [96]:
hight_sales=df[df["Customer"]=="Anu"]

In [97]:
hight_sales

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
12,13,2026-01-13,Anu,Clothing,Jeans,9,40878,4087,Credit Card,South
25,26,2026-06-15,Anu,Grocery,Tea,1,2808,628,Cash,West
37,38,2026-03-09,Anu,Stationery,Marker,2,3944,1077,Cash,South
47,48,2026-01-08,Anu,Furniture,Desk,7,259987,39739,Debit Card,South
50,51,2026-06-19,Anu,Furniture,Bookshelf,2,47278,10263,Debit Card,East
57,58,2026-08-17,Anu,Grocery,Cooking Oil,3,8211,1899,UPI,South
58,59,2026-08-23,Anu,Clothing,Shoes,8,7288,1476,UPI,South
74,75,2026-03-04,Anu,Clothing,Shirt,10,61570,16176,Debit Card,North
101,102,2026-03-24,Anu,Grocery,Rice,8,11800,2004,Credit Card,East
113,114,2026-03-26,Anu,Grocery,Rice,3,6321,1848,UPI,North
138,139,2026-02-14,Anu,Furniture,Table,3,112209,15164,Cash,South
156,157,2026-05-12,Anu,Stationery,File,7,4263,543,Debit Card,West
164,165,2026-06-12,Anu,Furniture,Table,6,78108,7561,Net Banking,South
177,178,2026-07-21,Anu,Clothing,Jeans,3,3396,492,Net Banking,North
199,200,2026-03-24,Anu,Electronics,Monitor,10,251520,50305,Cash,East
213,214,2026-08-01,Anu,Clothing,Dress,9,71640,19414,Net Banking,South
228,229,2026-02-02,Anu,Stationery,Marker,10,14430,3094,UPI,East
243,244,2026-02-05,Anu,Clothing,Shoes,5,25520,5950,Net Banking,South
244,245,2026-01-14,Anu,Clothing,Shirt,9,21132,4656,UPI,East
248,249,2026-06-04,Anu,Clothing,Jacket,1,575,83,Debit Card,East
267,268,2026-07-05,Anu,Furniture,Table,5,71760,20539,Cash,West
280,281,2026-04-30,Anu,Furniture,Sofa,6,213642,58584,UPI,East
297,298,2026-01-14,Anu,Clothing,Shirt,9,59454,17500,UPI,South
316,317,2026-01-03,Anu,Stationery,File,6,10080,1760,Debit Card,South
327,328,2026-03-22,Anu,Furniture,Desk,10,75540,17212,Credit Card,East
350,351,2026-01-23,Anu,Grocery,Cooking Oil,8,2720,354,Cash,East
407,408,2026-03-08,Anu,Grocery,Rice,1,1257,106,Cash,East
415,416,2026-07-12,Anu,Furniture,Table,5,194890,18234,Cash,East
422,423,2026-05-30,Anu,Electronics,Monitor,3,62772,12846,Cash,North
426,427,2026-06-25,Anu,Furniture,Sofa,5,171090,45990,Credit Card,South
431,432,2026-04-12,Anu,Clothing,Jacket,6,43476,7918,Cash,South
457,458,2026-04-08,Anu,Electronics,Laptop,1,16676,2863,Net Banking,East
459,460,2026-04-18,Anu,Stationery,Marker,10,12900,3020,Net Banking,North
488,489,2026-03-24,Anu,Clothing,Jeans,9,44496,10356,Debit Card,West

In [98]:
hight_sales=df[df["Quantity"]>5]

In [99]:
hight_sales

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
5,6,2026-06-08,Neha,Grocery,Rice,9,11250,2952,Net Banking,South
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South
10,11,2026-04-28,Vijay,Clothing,Dress,7,54229,15249,Debit Card,South
...,...,...,...,...,...,...,...,...,...,...
489,490,2026-08-04,Swathi,Stationery,Calculator,7,10010,2447,Debit Card,West
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South

In [100]:
df.sort_values("Sales")

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North
...,...,...,...,...,...,...,...,...,...,...
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
169,170,2026-05-29,Swathi,Electronics,Laptop,10,679620,111856,Cash,West
277,278,2026-02-23,Ravi,Electronics,Smartphone,10,747490,95487,Debit Card,North

In [101]:
df.sort_values("Profit")

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West
...,...,...,...,...,...,...,...,...,...,...
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
473,474,2026-08-11,Priya,Electronics,Smartphone,9,567090,151646,Cash,West
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
298,299,2026-03-25,Arun,Electronics,Headphones,10,534960,156830,Debit Card,West

In [102]:
Category_sales=df.groupby("Category")["Sales"].sum()

In [103]:
Category_sales

Category
Clothing        2248310
Electronics    22256321
Furniture      13063762
Grocery          797596
Stationery       601915
Name: Sales, dtype: int64

In [104]:
Category=df.groupby("Category")[["Sales","Profit"]].sum()

In [105]:
Category

                Sales   Profit
Category
Clothing      2248310   444567
Electronics  22256321  4258542
Furniture    13063762  2399870
Grocery        797596   148153
Stationery     601915   108090

In [106]:
Customer=df.groupby("Customer")[["Sales","Profit"]].sum()

In [107]:
Customer

            Sales  Profit
Customer
Aditya    1637408  253331
Akhil     2088969  437192
Anjali    1636343  247873
Anu       2181621  425429
Arun      2817469  654697
Divya     1282769  259239
Kiran     1591470  313723
Lakshmi   1833916  329242
Manoj     1576864  246208
Meena     2793148  491398
Neha      1590938  262175
Nikhil    1784018  320731
Pooja     2243126  481712
Priya     2323539  496235
Rahul      826114  147428
Ravi      2354172  390052
Sneha     1410967  284564
Suresh    1658293  267532
Swathi    3564632  722643
Vijay     1772128  327818

In [108]:
best_customer=Customer_sales["Sales"].idxmax()

In [109]:
print("best customer:",best_customer)
print("Sales:",Customer_sales.max())

best customer: Swathi
Sales: Sales     3564632
Profit     722643
dtype: int64

In [110]:
sales_report=df.groupby("Category").agg(
    total_sales=("Sales","sum"),
    average_sales=("Sales","mean"),
    total_profit=("Profit","sum"),
    total_quantity=("Quantity","sum")
)

print(sales_report)

             total_sales  average_sales  total_profit  total_quantity
Category
Clothing         2248310   23666.421053        444567             526
Electronics     22256321  229446.608247       4258542             529
Furniture       13063762  114594.403509       2399870             630
Grocery           797596    7975.960000        148153             577
Stationery        601915    6403.351064        108090             532

In [111]:
pivot=pd.pivot_table(
    df,
    values="Sales",
    index="Customer",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)

print(pivot)

Category  Clothing  Electronics  Furniture  Grocery  Stationery
Customer
Aditya       60234      1135900     391540     1420       48314
Akhil       190418       995544     826174    58906       17927
Anjali      112207       574194     890550    11286       48106
Anu         379425       498958    1224504    33117       45617
Arun        119341      1984593     637901    75634           0
Divya       113546       490594     619079    34740       24810
Kiran        10363       667444     841585    42948       29130
Lakshmi      39421       691204    1084851     8963        9477
Manoj        28025       954934     498947    64366       30592
Meena       199191      1891910     653513    25406       23128
Neha         33388       792018     675251    50727       39554
Nikhil       38690      1191851     495740    43606       14131
Pooja       138606      1764932     258293    40661       40634
Priya       127397      1648610     437067    94715       15750
Rahul       148714       220621     372506    22599       61674
Ravi        217423      1200764     883071    30560       22354
Sneha        48799      1008372     268155    62055       23586
Suresh      110258      1241462     246482    40473       19618
Swathi       71298      2501531     892993    33241       65569
Vijay        61566       800885     865560    22173       21944

In [112]:
df["Profit_margin"]=(df["Profit"]|df["Sales"])*100

In [113]:
df["Profit_margin"]

0      18553400
1         11100
2        819100
3        357400
4       1009300
         ...
495     1615800
496      988700
497    17944500
498     1605900
499     1599900
Name: Profit_margin, Length: 500, dtype: int64